### ISSUE TITLE
neo4j-noderank can't get started in neo4j version 1.9.3

### ISSUE THREAD

**Issue by Carrie0593** [graphaware/neo4j-noderank#1]
Is there any solution to use neo4j-noderank in neo4j version 1.9.3? I follow the readme instruction in https://github.com/graphaware/neo4j-noderank, the code is:

GraphAwareRuntime runtime = GraphAwareRuntimeFactory.createRuntime(database);  //where database is an instance of GraphDatabaseService
NodeRankModule module = new NodeRankModule("NR");
runtime.registerModule(module);
runtime.start();

and I also tried this:

GraphDatabaseService database = new TestGraphDatabaseFactory().newEmbeddedDatabaseBuilder(pathToDb)
    .loadPropertiesFromFile(this.getClass().getClassLoader().getResource("neo4j.properties").getPath())
    .newGraphDatabase();

RuntimeRegistry.getStartedRuntime(database);

but get the error below:

Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/core/GraphPropertiesImpl
    at com.graphaware.runtime.metadata.GraphPropertiesMetadataRepository.<init>(GraphPropertiesMetadataRepository.java:52)
    at com.graphaware.runtime.GraphAwareRuntimeFactory.createRuntime(GraphAwareRuntimeFactory.java:62)
    at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:491)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.core.GraphPropertiesImpl
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 14 more

**Comment by bachmanm** [comment]
I'm afraid the module is only supported in Neo4j 2.1 and 2.2. Please upgrade your Neo4j instance, preferably to 2.2.
