### ISSUE TITLE
`ga.noderank.getTopRanked` is already in use

### ISSUE THREAD

**Issue by jhb9** [graphaware/neo4j-noderank#11]
Can't start Neo4j once NodeRank is added,  neo4j.conf was edited per instructions and I made triple sure I was using all 3.0.3 versions.

Neo4j 3.0.3
graphaware-noderank-3.0.3.39.2.jar
graphaware-server-community-all-3.0.3.39.jar

2016-07-14 17:37:08.223+0000 INFO  Starting...
2016-07-14 17:37:08.942+0000 INFO  Bolt enabled on localhost:7687.
2016-07-14 17:37:10.150+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2016-07-14 17:37:10.164+0000 INFO  Running in a single-node architecture (Neo4j Community)
2016-07-14 17:37:10.174+0000 INFO  [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NR, using com.graphaware.module.noderank.NodeRankModuleBootstrapper
2016-07-14 17:37:10.176+0000 INFO  Constructing new module with ID: NR
2016-07-14 17:37:10.262+0000 INFO  Node Inclusion Policy set to com.graphaware.common.policy.composite.CompositeNodeInclusionPolicy@f5fc20ff
2016-07-14 17:37:10.276+0000 INFO  Sucessfully registered noderank procedure
2016-07-14 17:37:10.290+0000 INFO  Registering module NR with GraphAware Runtime.
2016-07-14 17:37:10.292+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2016-07-14 17:37:13.787+0000 INFO  Shutting down GraphAware Runtime... 
2016-07-14 17:37:13.787+0000 INFO  Shutting down module NR
2016-07-14 17:37:13.787+0000 INFO  Terminating task scheduler...
2016-07-14 17:37:13.788+0000 INFO  Task scheduler terminated successfully.
2016-07-14 17:37:13.788+0000 INFO  GraphAware Runtime shut down.
2016-07-14 17:37:13.796+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2016-07-14 17:37:13.800+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38d465f0' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38d465f0' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38d465f0' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:66)
    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38d465f0' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
    ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /Applications/neo4j-community-3.0.3/data/databases/cdpCamHop.db
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.server.CommunityNeoServer.lambda$static$31(CommunityNeoServer.java:55)
    at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@6c053151' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
    ... 10 more
Caused by: org.neo4j.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `ga.noderank.getTopRanked` is already in use.
    at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:54)
    at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:69)
    at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:127)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 12 more

**Comment by ikwattro** [comment]
Are you running a neo4j instance with the mac installer ? In that case our modules are not compatible.

If no, please output the content of your plugins directory. Thanks !

**Comment by jhb9** [comment]
I originally was using the Mac .dmg Neo4j installer but after reading about the compatibility issue removed it and am using the tar files under the /Applications/ folder.

My Plugins directory looks like the following:
$ ls -al
total 24832
drwxr-xr-x@  5 ... 170 Jul 13 15:31 .
drwxr-xr-x@ 17 ... 578 Jul 13 15:22 ..
-rw-r--r--@  1   ... 6148 Jul 13 15:31 .DS_Store
-rw-r--r--@  1   ... 18059 Jul 13 15:14 graphaware-noderank-3.0.3.39.2.jar
-rw-r--r--@  1   ... 12681253 Jul 13 14:46 graphaware-server-community-all-3.0.3.39.jar

**Comment by ikwattro** [comment]
@jhb9 Thanks for the report. I could reproduce the issue, we'll investigate and make a fix and notify you when it is released.

**Comment by ikwattro** [comment]
@jhb9 The has been fixed. It will take some time before the artifact will be available on maven.

In the meantime you can download the new snapshot from here  : https://s3-eu-west-1.amazonaws.com/graphaware/assets/libs/noderank-3.0.3.39.3-SNAPSHOT.jar

@bachmanm Can you prepare the new release, thanks !

**Comment by ikwattro** [comment]
@jhb9 New version released and available http://products.graphaware.com/download/noderank/graphaware-noderank-3.0.3.39.3.jar

**Comment by jhb9** [comment]
Got the new .jar and it appears to be working great.  Thanks!

**Comment by ikwattro** [comment]
Good to hear !
