### ISSUE TITLE
404

### ISSUE THREAD

**Issue by xghrbc1001** [graphaware/neo4j-noderank#12]
neo4j's version is 2.2.5.

neo4j-server.properties

```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
```

neo4j.properties

```
com.graphaware.runtime.enabled=true
com.graphaware.module.NR.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper
com.graphaware.module.NR.maxTopRankNodes=10
com.graphaware.module.NR.dampingFactor=0.85
com.graphaware.module.NR.propertyKey=nodeRank
com.graphaware.module.NR.node=hasLabel('C')
com.graphaware.module.NR.relationship=isType('B')
```

while we access this url
http://localhost:7478/graphaware/noderank/NR?limit=10
give me 404.

**Comment by ikwattro** [comment]
Hi,

The setting you are using : `dbms.unmanaged_extension_classes` is for neo4j 3.x.

You should use : `org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware` instead.

**Comment by xghrbc1001** [comment]
we use org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware
but neo4j can't startup. the exception as follow:

```
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-3
de8f383@5a7539e0==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:258) ~[neo4j-server-2.2.5.jar:2.2.5]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:117) [neo4j-server-2.2.5.jar:2.2.5]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:69) [neo4j-server-2.2.5.jar:2.2.5]
Caused by: java.lang.RuntimeException: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-3de8f383@5a7539e0==org.neo4j.serv
er.web.NeoServletContainer,-1,false
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:385) ~[neo4j-server-2.2.5.jar:2.2.5]
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:184) ~[neo4j-server-2.2.5.jar:2.2.5]
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:474) ~[neo4j-server-2.2.5.jar:2.2.5]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:230) ~[neo4j-server-2.2.5.jar:2.2.5]
        ... 2 common frames omitted
```

**Comment by ikwattro** [comment]
What is the plugin version you are using, also you don't use the mac or windows installer right ?

**Comment by xghrbc1001** [comment]
@ikwattro my version is 2.2.5, and linux ,not windows

**Comment by bachmanm** [comment]
and you are sure your Neo4j instance is running on 7478, right?

**Comment by ikwattro** [comment]
Also can you specify the version of the graphaware-framework you are using?

**Comment by xghrbc1001** [comment]
yes,on port 7478. and the version as below:
graphaware-noderank-2.2.5.35.2.jar
graphaware-server-community-all-2.2.5.35.jar

@bachmanm   @ikwattro

**Comment by bachmanm** [comment]
Is there any chance you could upgrade to 2.3, or even better to 3.0?  2.2 is quite an old version - we could give you support, but it would not be free of charge. Sorry about that.
