### ISSUE TITLE
No module of type com.graphaware.module.noderank.NodeRankModule with ID NR has been registered

### ISSUE THREAD

**Issue by ghost** [graphaware/neo4j-noderank#13]
I am trying to use NodeRank as per the instructions. Added the:
- **graphaware-noderank-3.0.6.43.3.jar**
- **graphaware-server-community-all-3.0.6.43.jar**
  into the plugins directory and updated the **~/neo4j-community-3.0.6/conf** file to include the following configuration settings:

```
#*****************************************************************
# NodeRank configuration
#*****************************************************************
com.graphaware.runtime.enabled=true

#NR becomes the module ID:
com.graphaware.module.NR.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper

#optional number of top ranked nodes to remember, the default is 10
com.graphaware.module.NR.maxTopRankNodes=1000

#optional daming factor, which is a number p such that a random node will be selected at any step of the algorithm
#with the probability 1-p (as opposed to following a random relationship). The default is 0.85
com.graphaware.module.NR.dampingFactor=0.85

#optional key of the property that gets written to the ranked nodes, default is "nodeRank"
com.graphaware.module.NR.propertyKey=nodeRank

#optionally specify nodes to rank using an expression-based node inclusion policy, default is all business (i.e. non-framework-internal) nodes
com.graphaware.module.NR.node=hasLabel(‘MyNodeType’)

#optionally specify relationships to follow using an expression-based relationship inclusion policy, default is all business (i.e. non-framework-internal) relationships
#com.graphaware.module.NR.relationship=isType('FRIEND_OF')
```

I am then calling the procedure with:

``` SQL
CALL ga.noderank.getTopRanked("NR", 10) YIELD node RETURN node
```

for which I am getting the following error:

```
Failed to invoke procedure `ga.noderank.getTopRanked`: Caused by: org.neo4j.graphdb.NotFoundException: No module of type com.graphaware.module.noderank.NodeRankModule with ID NR has been registered
```

What am I doing wrong?

**Comment by ikwattro** [comment]
You should also add this line to the configuration for enabling the framework : 

```
#For the framework to work at all, you need this
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
```

**Comment by ghost** [comment]
Thanks for the response. Tried it after including what you suggested but no luck. If this needs to be added it should be mentioned in the documentation. 

In any case, I am still getting the exact same error which refers to the module ID which can't be found - maybe I am doing something else wrong? Wrong name; calling it the wrong way... I don't know. Any ideas? Thanks in advance.

**Comment by ikwattro** [comment]
This is in the documentation of the framework.

Anyway, I copied your configuration and found an issue, do you have some logs showing some issues when neo4j is starting ?

I got this : 

```
2016-10-21 19:42:05.634+0000 INFO  Property key set to nodeRank
2016-10-21 19:42:05.635+0000 INFO  Max top rank nodes set to 1000
2016-10-21 19:42:05.635+0000 INFO  Damping factor set to 0.85
2016-10-21 19:42:05.672+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Unable to bootstrap module 1 Cannot handle (226) 'â'
java.lang.IllegalStateException: Cannot handle (226) 'â'
    at org.springframework.expression.spel.standard.Tokenizer.process(Tokenizer.java:271)
    at org.springframework.expression.spel.standard.Tokenizer.<init>(Tokenizer.java:84)
```

The quotes in this line : 

```
com.graphaware.module.NR.node=hasLabel(‘MyNodeType’)
```

are not valid, replacing them with normal single quotes fixed the issue : 

```
com.graphaware.module.NR.node=hasLabel('MyNodeType')
```

**Comment by ghost** [comment]
Thanks for taking the time to look at it, Christophe. It seems like that was it.  The exception message I was getting was not very helpful. 

It runs now. Just ran it for 10 nodes - need to play around a bit more to better understand how it works and what it is returning.
