### ISSUE TITLE
org.neo4j.graphdb.NotInTransactionException

### ISSUE THREAD

**Issue by magaton** [graphaware/neo4j-noderank#4]
When I put noderank jar along with graphaware community server in the plugin directory, neo4j doesn't start. The exception is:

Exception in thread "Thread-4" org.neo4j.graphdb.NotInTransactionException
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.java:71)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.java:82)
    at org.neo4j.tooling.GlobalGraphOperations.assertInUnterminatedTransaction(GlobalGraphOperations.java:273)
    at org.neo4j.tooling.GlobalGraphOperations.getAllNodes(GlobalGraphOperations.java:85)
    at com.graphaware.runtime.walk.RandomNodeSelector.randomNodeON(RandomNodeSelector.java:108)
    at com.graphaware.runtime.walk.RandomNodeSelector.selectNode(RandomNodeSelector.java:70)
    at com.graphaware.module.noderank.NodeRankModule.createInitialContext(NodeRankModule.java:71)
    at com.graphaware.module.noderank.NodeRankModule.createInitialContext(NodeRankModule.java:26)
    at com.graphaware.runtime.manager.ProductionTimerDrivenModuleManager.createFreshMetadata(ProductionTimerDrivenModuleManager.java:55)
    at com.graphaware.runtime.manager.ProductionTimerDrivenModuleManager.createFreshMetadata(ProductionTimerDrivenModuleManager.java:32)
    at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:133)
    at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:104)
    at com.graphaware.runtime.ProductionRuntime.loadMetadata(ProductionRuntime.java:81)
    at com.graphaware.runtime.BaseGraphAwareRuntime.startModules(BaseGraphAwareRuntime.java:170)
    at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:138)
    at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
    at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:145)
    at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:119)
    at com.graphaware.runtime.bootstrap.RuntimeKernelExtension$1.run(RuntimeKernelExtension.java:119)
    at java.lang.Thread.run(Thread.java:744)

**Comment by ikwattro** [comment]
Can you please specify the versions used for the graphaware-community-server, neo4j-noderank and neo4j itself, thanks

**Comment by magaton** [comment]
sure: neo4j 2.2.3 community edition, masters builds for graphaware-community-server and neo4j-noderank

**Comment by ikwattro** [comment]
Thanks, our modules have not been updated to neo4j2.2.3, due to this bug in neo4j data transactions : https://github.com/neo4j/neo4j/issues/4910

We hope this to be fixed in neo4j 2.2.4 

Can you confirm the same issue with neo4j 2.2.2 ?

**Comment by magaton** [comment]
I confirm. This is happening with 2.2.2 as well:

23:19:05.820 [main] INFO  c.g.s.GraphAwareCommunityNeoServer - Setting startup timeout to: 120000ms based on 120000
23:19:07.324 [main] INFO  c.g.r.b.RuntimeKernelExtension - GraphAware Runtime enabled, bootstrapping...
23:19:07.342 [main] INFO  c.g.r.b.RuntimeKernelExtension - Bootstrapping module with order 1, ID NR, using com.graphaware.module.noderank.NodeRankModuleBootstrapper
23:19:07.344 [main] INFO  c.g.m.n.NodeRankModuleBootstrapper - Constructing new module with ID: NR
23:19:07.398 [main] INFO  c.g.m.n.NodeRankModuleBootstrapper - Max top rank nodes set to 3
23:19:07.408 [main] INFO  c.g.runtime.BaseGraphAwareRuntime - Registering module NR with GraphAware Runtime.
23:19:07.409 [main] INFO  c.g.r.b.RuntimeKernelExtension - GraphAware Runtime bootstrapped, starting the Runtime...
2015-07-31 21:19:07.495+0000 INFO  [API] Successfully started database
23:19:07.502 [Thread-4] INFO  c.g.runtime.BaseGraphAwareRuntime - Starting GraphAware...
23:19:07.502 [Thread-4] INFO  c.g.runtime.BaseGraphAwareRuntime - Loading module metadata...
23:19:07.502 [Thread-4] INFO  c.g.r.manager.BaseModuleManager - Loading metadata for module NR
23:19:07.506 [Thread-4] INFO  c.g.r.manager.BaseModuleManager - Module NR seems to have been registered for the first time.
23:19:07.506 [Thread-4] INFO  c.g.r.manager.BaseModuleManager - Creating fresh metadata for module NR.
Exception in thread "Thread-4" org.neo4j.graphdb.NotInTransactionException
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.java:71)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getTopLevelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:104)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:111)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.instance(ThreadToStatementContextBridge.java:64)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.getNodeById(InternalAbstractGraphDatabase.java:1074)
    at com.graphaware.runtime.walk.RandomNodeSelector.randomNodeO1(RandomNodeSelector.java:89)
    at com.graphaware.runtime.walk.RandomNodeSelector.selectNode(RandomNodeSelector.java:64)
    at com.graphaware.module.noderank.NodeRankModule.createInitialContext(NodeRankModule.java:71)
    at com.graphaware.module.noderank.NodeRankModule.createInitialContext(NodeRankModule.java:26)
    at com.graphaware.runtime.manager.ProductionTimerDrivenModuleManager.createFreshMetadata(ProductionTimerDrivenModuleManager.java:55)
    at com.graphaware.runtime.manager.ProductionTimerDrivenModuleManager.createFreshMetadata(ProductionTimerDrivenModuleManager.java:32)
    at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:133)
    at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:104)
    at com.graphaware.runtime.ProductionRuntime.loadMetadata(ProductionRuntime.java:81)
    at com.graphaware.runtime.BaseGraphAwareRuntime.startModules(BaseGraphAwareRuntime.java:170)
    at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:138)
    at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
    at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:145)
    at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:119)
    at com.graphaware.runtime.bootstrap.RuntimeKernelExtension$1.run(RuntimeKernelExtension.java:119)
    at java.lang.Thread.run(Thread.java:744)
23:19:07.562 [main] INFO  c.g.s.GraphAwareCommunityNeoServer - Starting HTTP on port :7474 with 8 threads available

**Comment by bachmanm** [comment]
You seem to be using incompatible versions. If you're using NodeRank 2.2.2.32.2, then:
- the first 3 digits indicate Neo4j version compatibility, in this case 2.2.2
- the first 4 digits together indicate version of the GraphAware Framework you need to be using, in this case 2.2.2.32. It appears that you are using 2.2.2.33, for which the modules haven't been updated yet.

**Comment by magaton** [comment]
Yes, that was it. Thanks very much!
