### ISSUE TITLE
Error logging issues

### ISSUE THREAD

**Issue by phamann** [graphaware/neo4j-noderank#5]
We are having issues with our DB instance as the graphaware-noderank plugin is filling the console.log with errors leading to log files >100GB in size.

Therefore, whilst we diagnose the issue further is it possible to disable the logging within the graphaware runtime via configuration in the `neo4j-server.properties` file?
#### Version details:

Neo4j Community Edition: 2.2.5
noderank: 2.2.5.34.2
graphaware-server-community-all: 2.2.5.34
#### neo4j-server.properties:

```
com.graphaware.runtime.enabled=true

com.graphaware.module.concepts.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper

com.graphaware.module.concepts.maxTopRankNodes=20
com.graphaware.module.concepts.dampingFactor=0.85
com.graphaware.module.concepts.propertyKey=nodeRank
com.graphaware.module.concepts.node=hasLabel('Concept')
com.graphaware.module.concepts.relationship=isType('followed', 'viewed')
```
#### Sample error log:

```
org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 0): Method call: Method isType(java.lang.String,java.lang.String) cannot be found on com.graphaware.common.policy.spel.RelationshipExpressions type
        at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:211) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:125) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:85) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:153) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at com.graphaware.common.policy.spel.SpelRelationshipInclusionPolicy.include(SpelRelationshipInclusionPolicy.java:55) ~[graphaware-server-community-all-2.2.5.34.jar:na]
        at com.graphaware.common.policy.composite.CompositeRelationshipInclusionPolicy.include(CompositeRelationshipInclusionPolicy.java:41) ~[graphaware-server-community-all-2.2.5.34.jar:na]
[...]
```

**Comment by bachmanm** [comment]
You should use:
`isType('followed') || isType('viewed')`

Logging can be disabled in logback - see https://github.com/graphaware/neo4j-framework/tree/master/runtime#logging

**Comment by phamann** [comment]
@bachmanm Thank you for the speedy response. Do you think misconfiguration of  `isType('followed') || isType('viewed')` will be causing the high error levels?

**Comment by bachmanm** [comment]
definitely

**Comment by phamann** [comment]
Thank you for your help :smile:

**Comment by bachmanm** [comment]
No worries!
